//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkFast.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThinkFast.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo.
        /// </summary>
        public static string Combo {
            get {
                return ResourceManager.GetString("Combo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        public static string Division {
            get {
                return ResourceManager.GetString("Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To divide by 5, first multiply by 2, and then divide the result by 10..
        /// </summary>
        public static string Division5Message {
            get {
                return ResourceManager.GetString("Division5Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To divide by a single-digit number, we divide the original multi-digit number into convenient parts, which will be exactly divisible by a single-digit number..
        /// </summary>
        public static string DivisionOneMessage {
            get {
                return ResourceManager.GetString("DivisionOneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtraction.
        /// </summary>
        public static string Minus {
            get {
                return ResourceManager.GetString("Minus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To subtract 7, subtract 10 and add 3..
        /// </summary>
        public static string Minus7Message {
            get {
                return ResourceManager.GetString("Minus7Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To subtract 8, subtract 10 and add 2..
        /// </summary>
        public static string Minus8Message {
            get {
                return ResourceManager.GetString("Minus8Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To subtract 9, subtract 10 and add 1..
        /// </summary>
        public static string Minus9Message {
            get {
                return ResourceManager.GetString("Minus9Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When subtracting multi-digit numbers, you need to divide the number that you subtract into digits..
        /// </summary>
        public static string MinusMultiMessage {
            get {
                return ResourceManager.GetString("MinusMultiMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication.
        /// </summary>
        public static string Multiplication {
            get {
                return ResourceManager.GetString("Multiplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To multiply any number by 11, you need to multiply this number by 10, and then add the number itself to the result..
        /// </summary>
        public static string Multiplication11Message {
            get {
                return ResourceManager.GetString("Multiplication11Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To orally multiply a multiple of 4 by 25, divide it by 4 and multiply it by 100..
        /// </summary>
        public static string Multiplication25_4Message {
            get {
                return ResourceManager.GetString("Multiplication25_4Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To verbally multiply a number by 25, it is multiplied by 100 and divided by 4..
        /// </summary>
        public static string Multiplication25Message {
            get {
                return ResourceManager.GetString("Multiplication25Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiply by 4 is to multiply by 2 twice..
        /// </summary>
        public static string Multiplication4Message {
            get {
                return ResourceManager.GetString("Multiplication4Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To multiply an even number by 5, divide it by 2 and then multiply by 10..
        /// </summary>
        public static string Multiplication5_2Message {
            get {
                return ResourceManager.GetString("Multiplication5_2Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To multiply by 5 an odd number, it is multiplied by 10, and then divided by 2..
        /// </summary>
        public static string Multiplication5Message {
            get {
                return ResourceManager.GetString("Multiplication5Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiply by 8 is to multiply by 2 three times..
        /// </summary>
        public static string Multiplication8Message {
            get {
                return ResourceManager.GetString("Multiplication8Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To multiply any number by 9, you need to multiply this number by 10, and then subtract the number itself from the result..
        /// </summary>
        public static string Multiplication9Message {
            get {
                return ResourceManager.GetString("Multiplication9Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To multiply multi-digit numbers, you need to mentally break one of these numbers into digits..
        /// </summary>
        public static string MultiplicationMultyMessage {
            get {
                return ResourceManager.GetString("MultiplicationMultyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To multiply a multi-digit number by a single-digit number, you need to split the multi-digit number into digits, multiply each by a single-digit number and sum the results..
        /// </summary>
        public static string MultiplicationMultyOneMessage {
            get {
                return ResourceManager.GetString("MultiplicationMultyOneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition.
        /// </summary>
        public static string Plus {
            get {
                return ResourceManager.GetString("Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To simplify the calculations of the numbers 7,8,9, you need to round them up to 10, and then subtract the increase..
        /// </summary>
        public static string Plus_7_8_9_Message {
            get {
                return ResourceManager.GetString("Plus_7_8_9_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To sum up multi-digit numbers, we divide them into digits (hundreds, tens, ones) and sum them up one by one..
        /// </summary>
        public static string PlusMultiMessage {
            get {
                return ResourceManager.GetString("PlusMultiMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PupsoCount.
        /// </summary>
        public static string PupsoCount {
            get {
                return ResourceManager.GetString("PupsoCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
    }
}
